### Files: CSV format Lecture Notes

Download to your PC CSV file "Annual Enterprise Survey: 2018 Financial Year (Provision)-CSV" at the following link: https://www.stats.govt.nz/large-datasets/csv-files-for-download/

In [ ]:
import csv
import os

In [8]:
[col for col in os.listdir(r'C:\Users\kulse\OneDrive\Рабочий стол\practice\assignment')]

['3w.ipynb',
 'annual-enterprise-survey-2018-financial-year-provisional-csv.csv',
 'arithmetics.py',
 'classes.py',
 'constructor.ipynb',
 'Files_csv_en.ipynb',
 'inheritance.ipynb',
 'Module_advanced_en.ipynb',
 'Module_intro_en.ipynb',
 'Module_method_import_en.ipynb',
 '__pycache__']

In [17]:
import csv

data = []
with open('annual-enterprise-survey-2018-financial-year-provisional-csv.csv', mode='r', encoding='utf-8') as file:
    csv_reader = csv.reader(file)
    for row in csv_reader:
        data.append(row)
        
print(data[:1])


[['Year', 'Industry_aggregation_NZSIOC', 'Industry_code_NZSIOC', 'Industry_name_NZSIOC', 'Units', 'Variable_code', 'Variable_name', 'Variable_category', 'Value', 'Industry_code_ANZSIC06']]


### Expected result:
```
[['Year', 'Industry_aggregation_NZSIOC', 'Industry_code_NZSIOC', 'Industry_name_NZSIOC', 'Units', 'Variable_code', 'Variable_name', 'Variable_category', 'Value', 'Industry_code_ANZSIC06']]
```

In [18]:
print(data[1:5])

[['2018', 'Level 1', '99999', 'All industries', 'Dollars (millions)', 'H01', 'Total income', 'Financial performance', '691859', 'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'], ['2018', 'Level 1', '99999', 'All industries', 'Dollars (millions)', 'H04', 'Sales, government funding, grants and subsidies', 'Financial performance', '605766', 'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'], ['2018', 'Level 1', '99999', 'All industries', 'Dollars (millions)', 'H05', 'Interest, dividends and donations', 'Financial performance', '63509', 'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'], ['2018', 'Level 1', '99999', 'All industries', 'Dollars (millions)', 'H07', 'Non-operating income', 'Financial performance', '22583', 'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O7

### Expected result:
```
[['2018', 'Level 1', '99999', 'All industries', 'Dollars (millions)', 'H01', 'Total income', 'Financial performance', '691859', 'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'], ['2018', 'Level 1', '99999', 'All industries', 'Dollars (millions)', 'H04', 'Sales, government funding, grants and subsidies', 'Financial performance', '605766', 'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'], ['2018', 'Level 1', '99999', 'All industries', 'Dollars (millions)', 'H05', 'Interest, dividends and donations', 'Financial performance', '63509', 'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'], ['2018', 'Level 1', '99999', 'All industries', 'Dollars (millions)', 'H07', 'Non-operating income', 'Financial performance', '22583', 'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'], ['2018', 'Level 1', '99999', 'All industries', 'Dollars (millions)', 'H08', 'Total expenditure', 'Financial performance', '597623', 'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)']]
```

In [19]:
print(data[-5:])

[['2013', 'Level 3', 'ZZ11', 'Food product manufacturing', 'Percentage', 'H37', 'Quick ratio', 'Financial ratios', '52', 'ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119'], ['2013', 'Level 3', 'ZZ11', 'Food product manufacturing', 'Percentage', 'H38', 'Margin on sales of goods for resale', 'Financial ratios', '40', 'ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119'], ['2013', 'Level 3', 'ZZ11', 'Food product manufacturing', 'Percentage', 'H39', 'Return on equity', 'Financial ratios', '12', 'ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119'], ['2013', 'Level 3', 'ZZ11', 'Food product manufacturing', 'Percentage', 'H40', 'Return on total assets', 'Financial ratios', '5', 'ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119'], ['2013', 'Level 3', 'ZZ11', 'Food product manufacturing', 'Percentage', 'H41', 'Liabilities structure', 'Financial ratios', '46', 'ANZSIC06 groups C111, C112, C113, C114, C

### Expected result:
```
[['2013', 'Level 3', 'ZZ11', 'Food product manufacturing', 'Percentage', 'H37', 'Quick ratio', 'Financial ratios', '52', 'ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119'], ['2013', 'Level 3', 'ZZ11', 'Food product manufacturing', 'Percentage', 'H38', 'Margin on sales of goods for resale', 'Financial ratios', '40', 'ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119'], ['2013', 'Level 3', 'ZZ11', 'Food product manufacturing', 'Percentage', 'H39', 'Return on equity', 'Financial ratios', '12', 'ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119'], ['2013', 'Level 3', 'ZZ11', 'Food product manufacturing', 'Percentage', 'H40', 'Return on total assets', 'Financial ratios', '5', 'ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119'], ['2013', 'Level 3', 'ZZ11', 'Food product manufacturing', 'Percentage', 'H41', 'Liabilities structure', 'Financial ratios', '46', 'ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119']]
```

----
### 1. Calculate how many different levels of aggregation of the industry exist (Industry_aggregation_NZSIOC)

In [54]:
import csv

unique_levels = set()

def analyze_data(data):
    header = data[0]  
    rows = data[1:]

    aggregation_index = header.index("Industry_aggregation_NZSIOC")

    for row in rows:
        unique_levels.add(row[aggregation_index])

file_path = "annual-enterprise-survey-2018-financial-year-provisional-csv.csv"
with open(file_path, mode="r") as file:
    csv_reader = csv.reader(file)
    data = list(csv_reader)

analyze_data(data)




In [22]:
print(unique_levels)
print(len(unique_levels))

{'Level 1', 'Level 3', 'Level 4'}
3


### Expected result:
```
{'Level 4', 'Level 3', 'Level 1'}
3
```

### 2. Calculate how many different industries (Industry_name_nzsioc) exist, and return the list of these unique industries.

In [38]:
import csv
unique_industries = set()

def analyze_industries(data):
    header = data[0]  
    rows = data[1:]   
    industry_index = header.index("Industry_name_NZSIOC")
    for row in rows:
        if row[industry_index]:
            unique_industries.add(row[industry_index].strip())

file_path = "annual-enterprise-survey-2018-financial-year-provisional-csv.csv"
with open(file_path, mode="r") as file:
    csv_reader = csv.reader(file)
    data = list(csv_reader)

analyze_industries(data)



In [39]:
print(unique_industries)
print(len(unique_industries))

{'Poultry, Deer and Other Livestock Farming', 'Building Cleaning, Pest Control and Other Support Services', 'Public order, safety and regulatory services', 'Transport, Postal and Warehousing', 'Printing', 'Construction Services', 'Veterinary and Other Professional Services', 'Tertiary Education', 'Fishing and Aquaculture', 'Retail Trade and Accommodation', 'Dairy Cattle Farming', 'Horticulture and Fruit Growing', 'Motor Vehicle and Motor Vehicle Parts Wholesaling', 'Property Operators and Real Estate Services', 'Furniture Manufacturing', 'Pulp, Paper and Converted Paper Product Manufacturing', 'Finance', 'Polymer Product and Rubber Product Manufacturing', 'Preschool Education', 'Non-Metallic Mineral Product Manufacturing', 'Fabricated Metal Product Manufacturing', 'Textile, Leather, Clothing and Footwear Manufacturing', 'Accommodation and Food Services', 'Heritage and Artistic Activities', 'Education and Training', 'Clothing, Knitted Products and Footwear Manufacturing', 'Transport Equ

### Expected result:
```
{'Electricity, Gas, Water and Waste Services', 'Insurance', 'Recreational, Clothing, Footwear and Personal Accessory Retailing', 'Auxiliary Finance and Insurance Services', 'Non-Financial Asset Leasing', 'Education and Training', 'Textile and Leather Manufacturing', 'Commission Based Wholesaling', 'Financial and Insurance Services', 'Supermarket, Grocery Stores and Specialised Food Retailing', 'Information Media and Telecommunications', 'Legal and Accounting Services', 'Hospitals', 'Basic Chemical and Chemical Product Manufacturing', 'Motor Vehicle and Motor Vehicle Parts Wholesaling', 'Transport, Postal and Warehousing', 'Other Goods Wholesaling', 'Machinery Manufacturing', 'Food and Beverage Services', 'Health and General Insurance', 'Sport and Recreation Activities', 'Horticulture and Fruit Growing', 'Travel Agency and Tour Arrangement Services', 'Petroleum and Coal Product Manufacturing', 'Sheep, Beef Cattle and Grain Farming', 'Professional, Scientific, Technical, Administrative and Support Services', 'Non-Residential Building Construction', 'Heritage and Artistic Activities', 'Dairy Cattle Farming', 'Food Product Manufacturing', 'Mining', 'Financial Asset Investing', 'Clothing, Knitted Products and Footwear Manufacturing', 'Basic Chemical and Basic Polymer Manufacturing', 'Wholesale Trade', 'Agriculture, Forestry and Fishing', 'Personal Care, Funeral and Other Personal Services', 'Transport Equipment Manufacturing', 'All industries', 'Rental and Hiring Services (except Real Estate)', 'Property Operators and Real Estate Services', 'Heavy and Civil Engineering Construction', 'Food product manufacturing', 'Construction Services', 'Machinery and Other Equipment Manufacturing', 'Other Services', 'Banking and Financing', 'Health Care and Social Assistance', 'Information Media Services', 'Electronic and Electrical Equipment Manufacturing', 'Gambling Activities', 'Employment and Other Administrative Services', 'Warehousing and Storage Services', 'Retail Trade and Accommodation', 'Finance', 'Water, Sewerage, Drainage and Waste Services', 'Arts and Recreation Services', 'Road Transport', 'Printing', 'Furniture and Other Manufacturing', 'Furniture, Electrical and Hardware Retailing', 'Residential Care Services and Social Assistance', 'Civil, Professional and Other Interest Groups', 'Life Insurance', 'Building Construction', 'Other Manufacturing', 'Accommodation', 'Rail, Water, Air and Other Transport', 'Telecommunications, Internet and Library Services', 'Manufacturing', 'Motor Vehicle and Motor Vehicle Parts and Fuel Retailing', 'Beverage and Tobacco Product Manufacturing', 'Primary Metal and Metal Product Manufacturing', 'Preschool Education', 'Fabricated Metal Product Manufacturing', 'Public Order, Safety and Regulatory Services', 'Wood Product Manufacturing', 'Poultry, Deer and Other Livestock Farming', 'School Education', 'Administrative and Support Services', 'Non-Residential Property Operation', 'Repair and Maintenance', 'Polymer Product and Rubber Product Manufacturing', 'Accommodation and Food Services', 'Pulp, Paper and Converted Paper Product Manufacturing', 'Residential Building Construction', 'Adult, Community and Other Education', 'Non-Metallic Mineral Product Manufacturing', 'Pharmaceutical, Cleaning and Other Chemical Manufacturing', 'Non-Store and Commission Based Retailing', 'Rental, Hiring and Real Estate Services', 'Fertiliser and Pesticide Manufacturing', 'Electricity and Gas Supply', 'Forestry and Logging', 'Furniture Manufacturing', 'Pharmaceutical and Other Store Based Retailing', 'Department Stores', 'Transport Support Services', 'Construction', 'Public order, safety and regulatory services', 'Tertiary Education', 'Medical and Other Health Care Services', 'Postal, Courier, Transport Support, and Warehousing Services', 'Basic Material Wholesaling', 'Computer System Design and Related Services', 'Arts, Recreation and Other Services', 'Postal and Courier Pick Up and Delivery Services', 'Real Estate Services', 'Advertising, Market Research and Management Services', 'Veterinary and Other Professional Services', 'Fishing and Aquaculture', 'Machinery and Equipment Wholesaling', 'Professional, Scientific and Technical Services', 'Grocery, Liquor and Tobacco Product Wholesaling', 'Other Store-Based Retailing and Non Store Retailing', 'Agriculture, Forestry and Fishing Support Services and Hunting', 'Building Cleaning, Pest Control and Other Support Services', 'Textile, Leather, Clothing and Footwear Manufacturing', 'Scientific, Architectural and Engineering Services'}
119
```

### 3. Create new CSV files containing data only in the same year. Example: 2018.csv, 2017.csv, etc.

In [47]:
import csv
file_path = "annual-enterprise-survey-2018-financial-year-provisional-csv.csv"

with open(file_path, mode="r") as file:
    csv_reader = csv.reader(file)
    data = list(csv_reader)
header = data[0]
rows = data[1:]
year_index = header.index("Year")

unique_years = set()
data_by_year = {}

for row in rows:
    year = row[year_index].strip()  
    if year:  
        unique_years.add(year)
        if year not in data_by_year:
            data_by_year[year] = []
        data_by_year[year].append(row)

print(unique_years)



{'2014', '2013', '2016', '2017', '2018', '2015'}


### Expected result:
```
{'2013', '2018', '2017', '2014', '2016', '2015'}
```

In [ ]:
for year, year_rows in data_by_year.items():
    output_file = f"{year}.csv"
    with open(output_file, mode="w", newline="") as file:
        writer = csv.writer(file)
        writer.writerow(header) 
        writer.writerows(year_rows) 
    print(f"{output_file} is written")

2018.csv is written
2017.csv is written
2016.csv is written
2015.csv is written
2014.csv is written
2013.csv is written


### Expected result:
```
2013.csv is written
2018.csv is written
2017.csv is written
2014.csv is written
2016.csv is written
2015.csv is written
```

In [45]:
import os

list_of_files = [file for file in os.listdir("./") if file.endswith(".csv")]
print(list_of_files)

['2013.csv', '2014.csv', '2015.csv', '2016.csv', '2017.csv', '2018.csv', 'annual-enterprise-survey-2018-financial-year-provisional-csv.csv']


### Expected result:
```
['2018.csv', '2015.csv', '2014.csv', '2016.csv', '2017.csv', '2013.csv', 'annual-enterprise-survey-2018-financial-year-provisional-csv.csv']
```


** Please open the CSV files you just created and check whether the year in these files with the file name coincides. **

### 4. Additionally: just try to analyze more data from the CSV file using all your knowledge. Example: sorting data on a specific column.

In [59]:
import csv
file_path = "annual-enterprise-survey-2018-financial-year-provisional-csv.csv"

print(sorted(unique_industries))
print(sorted(unique_levels))
print(sorted(unique_years))

['Accommodation', 'Accommodation and Food Services', 'Administrative and Support Services', 'Adult, Community and Other Education', 'Advertising, Market Research and Management Services', 'Agriculture, Forestry and Fishing', 'Agriculture, Forestry and Fishing Support Services and Hunting', 'All industries', 'Arts and Recreation Services', 'Arts, Recreation and Other Services', 'Auxiliary Finance and Insurance Services', 'Banking and Financing', 'Basic Chemical and Basic Polymer Manufacturing', 'Basic Chemical and Chemical Product Manufacturing', 'Basic Material Wholesaling', 'Beverage and Tobacco Product Manufacturing', 'Building Cleaning, Pest Control and Other Support Services', 'Building Construction', 'Civil, Professional and Other Interest Groups', 'Clothing, Knitted Products and Footwear Manufacturing', 'Commission Based Wholesaling', 'Computer System Design and Related Services', 'Construction', 'Construction Services', 'Dairy Cattle Farming', 'Department Stores', 'Education and